package com.weproov.app.models;

import com.weproov.app.R;

public class Country {

	public String name;
	public String ISO3166;
	public int phone;
	public int order;
	public int res;

	public Country(String name, String ISO3166, int phone, int order, int res) {
		this.name = name;
		this.ISO3166 = ISO3166;
		this.phone = phone;
		this.order = order;
		this.res = res;
	}


	public static final Country[] COUNTRIES = new Country[]{
			new Country("Afghanistan", "af", 93, 0, R.drawable.af),
			new Country("Albania", "al", 355, 0, R.drawable.al),
			new Country("Algeria", "dz", 213, 0, R.drawable.dz),
			new Country("American Samoa", "as", 1684, 0, R.drawable.as),
			new Country("Andorra", "ad", 376, 0, R.drawable.ad),
			new Country("Angola", "ao", 244, 0, R.drawable.ao),
			new Country("Anguilla", "ai", 1264, 0, R.drawable.ai),
			new Country("Antigua and Barbuda", "ag", 1268, 0, R.drawable.ag),
			new Country("Argentina", "ar", 54, 0, R.drawable.ar),
			new Country("Armenia", "am", 374, 0, R.drawable.am),
			new Country("Aruba", "aw", 297, 0, R.drawable.aw),
			new Country("Australia", "au", 61, 0, R.drawable.au),
			new Country("Austria", "at", 43, 0, R.drawable.at),
			new Country("Azerbaijan", "az", 994, 0, R.drawable.az),
			new Country("Bahamas", "bs", 1242, 0, R.drawable.bs),
			new Country("Bahrain", "bh", 973, 0, R.drawable.bh),
			new Country("Bangladesh", "bd", 880, 0, R.drawable.bd),
			new Country("Barbados", "bb", 1246, 0, R.drawable.bb),
			new Country("Belarus", "by", 375, 0, R.drawable.by),
			new Country("Belgium", "be", 32, 0, R.drawable.be),
			new Country("Belize", "bz", 501, 0, R.drawable.bz),
			new Country("Benin", "bj", 229, 0, R.drawable.bj),
			new Country("Bermuda", "bm", 1441, 0, R.drawable.bm),
			new Country("Bhutan", "bt", 975, 0, R.drawable.bt),
			new Country("Bolivia", "bo", 591, 0, R.drawable.bo),
			new Country("Bosnia and Herzegovina", "ba", 387, 0, R.drawable.ba),
			new Country("Botswana", "bw", 267, 0, R.drawable.bw),
			new Country("Brazil", "br", 55, 0, R.drawable.br),
			new Country("British Indian Ocean Territory", "io", 246, 0, R.drawable.io),
			new Country("British Virgin Islands", "vg", 1284, 0, R.drawable.vg),
			new Country("Brunei", "bn", 673, 0, R.drawable.bn),
			new Country("Bulgaria", "bg", 359, 0, R.drawable.bg),
			new Country("Burkina Faso", "bf", 226, 0, R.drawable.bf),
			new Country("Burundi", "bi", 257, 0, R.drawable.bi),
			new Country("Cambodia", "kh", 855, 0, R.drawable.kh),
			new Country("Cameroon", "cm", 237, 0, R.drawable.cm),
			new Country("Canada", "ca", 1, 1, R.drawable.ca),
			new Country("Cape Verde", "cv", 238, 0, R.drawable.cv),
			// new Country("Caribbean Netherlands", "bq", 599, 1, R.drawable.bq),
			new Country("Cayman Islands", "ky", 1345, 0, R.drawable.ky),
			new Country("Central African Republic", "cf", 236, 0, R.drawable.cf),
			new Country("Chad", "td", 235, 0, R.drawable.td),
			new Country("Chile", "cl", 56, 0, R.drawable.cl),
			new Country("China", "cn", 86, 0, R.drawable.cn),
			new Country("Colombia", "co", 57, 0, R.drawable.co),
			new Country("Comoros", "km", 269, 0, R.drawable.km),
			new Country("Congo (DRC)", "cd", 243, 0, R.drawable.cd),
			new Country("Congo (Republic)", "cg", 242, 0, R.drawable.cg),
			new Country("Cook Islands", "ck", 682, 0, R.drawable.ck),
			new Country("Costa Rica", "cr", 506, 0, R.drawable.cr),
			new Country("Cote d'Ivoire", "ci", 225, 0, R.drawable.ci),
			new Country("Croatia", "hr", 385, 0, R.drawable.hr),
			new Country("Cuba", "cu", 53, 0, R.drawable.cu),
			// new Country("Curacao", "cw", 599, 0, R.drawable.cw),
			new Country("Cyprus", "cy", 357, 0, R.drawable.cy),
			new Country("Czech Republic", "cz", 420, 0, R.drawable.cz),
			new Country("Denmark", "dk", 45, 0, R.drawable.dk),
			new Country("Djibouti", "dj", 253, 0, R.drawable.dj),
			new Country("Dominica", "dm", 1767, 0, R.drawable.dm),
			new Country("Dominican Republic", "do", 1, 2, R.drawable.dom),
			new Country("Ecuador", "ec", 593, 0, R.drawable.ec),
			new Country("Egypt", "eg", 20, 0, R.drawable.eg),
			new Country("El Salvador", "sv", 503, 0, R.drawable.sv),
			new Country("Equatorial Guinea", "gq", 240, 0, R.drawable.gq),
			new Country("Eritrea", "er", 291, 0, R.drawable.er),
			new Country("Estonia", "ee", 372, 0, R.drawable.ee),
			new Country("Ethiopia", "et", 251, 0, R.drawable.et),
			new Country("Falkland Islands", "fk", 500, 0, R.drawable.fk),
			new Country("Faroe Islands", "fo", 298, 0, R.drawable.fo),
			new Country("Fiji", "fj", 679, 0, R.drawable.fj),
			new Country("Finland", "fi", 358, 0, R.drawable.fi),
			new Country("France", "fr", 33, 0, R.drawable.fr),
			new Country("French Guiana", "gf", 594, 0, R.drawable.gf),
			new Country("French Polynesia", "pf", 689, 0, R.drawable.pf),
			new Country("Gabon", "ga", 241, 0, R.drawable.ga),
			new Country("Gambia", "gm", 220, 0, R.drawable.gm),
			new Country("Georgia", "ge", 995, 0, R.drawable.ge),
			new Country("Germany", "de", 49, 0, R.drawable.de),
			new Country("Ghana", "gh", 233, 0, R.drawable.gh),
			new Country("Gibraltar", "gi", 350, 0, R.drawable.gi),
			new Country("Greece", "gr", 30, 0, R.drawable.gr),
			new Country("Greenland", "gl", 299, 0, R.drawable.gl),
			new Country("Grenada", "gd", 1473, 0, R.drawable.gd),
			new Country("Guadeloupe", "gp", 590, 0, R.drawable.gp),
			new Country("Guam", "gu", 1671, 0, R.drawable.gu),
			new Country("Guatemala", "gt", 502, 0, R.drawable.gt),
			new Country("Guinea", "gn", 224, 0, R.drawable.gn),
			new Country("Guinea-Bissau", "gw", 245, 0, R.drawable.gw),
			new Country("Guyana", "gy", 592, 0, R.drawable.gy),
			new Country("Haiti", "ht", 509, 0, R.drawable.ht),
			new Country("Honduras", "hn", 504, 0, R.drawable.hn),
			new Country("Hong Kong", "hk", 852, 0, R.drawable.hk),
			new Country("Hungary", "hu", 36, 0, R.drawable.hu),
			new Country("Iceland", "is", 354, 0, R.drawable.is),
			new Country("India", "in", 91, 0, R.drawable.in),
			new Country("Indonesia", "id", 62, 0, R.drawable.id),
			new Country("Iran", "ir", 98, 0, R.drawable.ir),
			new Country("Iraq", "iq", 964, 0, R.drawable.iq),
			new Country("Ireland", "ie", 353, 0, R.drawable.ie),
			new Country("Israel", "il", 972, 0, R.drawable.il),
			new Country("Italy", "it", 39, 0, R.drawable.it),
			new Country("Jamaica", "jm", 1876, 0, R.drawable.jm),
			new Country("Japan", "jp", 81, 0, R.drawable.jp),
			new Country("Jordan", "jo", 962, 0, R.drawable.jo),
			new Country("Kazakhstan", "kz", 7, 1, R.drawable.kz),
			new Country("Kenya", "ke", 254, 0, R.drawable.ke),
			new Country("Kiribati", "ki", 686, 0, R.drawable.ki),
			new Country("Kuwait", "kw", 965, 0, R.drawable.kw),
			new Country("Kyrgyzstan", "kg", 996, 0, R.drawable.kg),
			new Country("Laos", "la", 856, 0, R.drawable.la),
			new Country("Latvia", "lv", 371, 0, R.drawable.lv),
			new Country("Lebanon", "lb", 961, 0, R.drawable.lb),
			new Country("Lesotho", "ls", 266, 0, R.drawable.ls),
			new Country("Liberia", "lr", 231, 0, R.drawable.lr),
			new Country("Libya", "ly", 218, 0, R.drawable.ly),
			new Country("Liechtenstein", "li", 423, 0, R.drawable.li),
			new Country("Lithuania", "lt", 370, 0, R.drawable.lt),
			new Country("Luxembourg", "lu", 352, 0, R.drawable.lu),
			new Country("Macau", "mo", 853, 0, R.drawable.mo),
			new Country("Macedonia", "mk", 389, 0, R.drawable.mk),
			new Country("Madagascar", "mg", 261, 0, R.drawable.mg),
			new Country("Malawi", "mw", 265, 0, R.drawable.mw),
			new Country("Malaysia", "my", 60, 0, R.drawable.my),
			new Country("Maldives", "mv", 960, 0, R.drawable.mv),
			new Country("Mali", "ml", 223, 0, R.drawable.ml),
			new Country("Malta", "mt", 356, 0, R.drawable.mt),
			new Country("Marshall Islands", "mh", 692, 0, R.drawable.mh),
			new Country("Martinique", "mq", 596, 0, R.drawable.mq),
			new Country("Mauritania", "mr", 222, 0, R.drawable.mr),
			new Country("Mauritius", "mu", 230, 0, R.drawable.mu),
			new Country("Mexico", "mx", 52, 0, R.drawable.mx),
			new Country("Micronesia", "fm", 691, 0, R.drawable.fm),
			new Country("Moldova", "md", 373, 0, R.drawable.md),
			new Country("Monaco", "mc", 377, 0, R.drawable.mc),
			new Country("Mongolia", "mn", 976, 0, R.drawable.mn),
			new Country("Montenegro", "me", 382, 0, R.drawable.me),
			new Country("Montserrat", "ms", 1664, 0, R.drawable.ms),
			new Country("Morocco", "ma", 212, 0, R.drawable.ma),
			new Country("Mozambique", "mz", 258, 0, R.drawable.mz),
			new Country("Myanmar", "mm", 95, 0, R.drawable.mm),
			new Country("Namibia", "na", 264, 0, R.drawable.na),
			new Country("Nauru", "nr", 674, 0, R.drawable.nr),
			new Country("Nepal", "np", 977, 0, R.drawable.np),
			new Country("Netherlands", "nl", 31, 0, R.drawable.nl),
			new Country("New Caledonia", "nc", 687, 0, R.drawable.nc),
			new Country("New Zealand", "nz", 64, 0, R.drawable.nz),
			new Country("Nicaragua", "ni", 505, 0, R.drawable.ni),
			new Country("Niger", "ne", 227, 0, R.drawable.ne),
			new Country("Nigeria", "ng", 234, 0, R.drawable.ng),
			new Country("Niue", "nu", 683, 0, R.drawable.nu),
			new Country("Norfolk Island", "nf", 672, 0, R.drawable.nf),
			new Country("North Korea", "kp", 850, 0, R.drawable.kp),
			new Country("Northern Mariana Islands", "mp", 1670, 0, R.drawable.mp),
			new Country("Norway", "no", 47, 0, R.drawable.no),
			new Country("Oman", "om", 968, 0, R.drawable.om),
			new Country("Pakistan", "pk", 92, 0, R.drawable.pk),
			new Country("Palau", "pw", 680, 0, R.drawable.pw),
			new Country("Palestine", "ps", 970, 0, R.drawable.ps),
			new Country("Panama", "pa", 507, 0, R.drawable.pa),
			new Country("Papua New Guinea", "pg", 675, 0, R.drawable.pg),
			new Country("Paraguay", "py", 595, 0, R.drawable.py),
			new Country("Peru", "pe", 51, 0, R.drawable.pe),
			new Country("Philippines", "ph", 63, 0, R.drawable.ph),
			new Country("Poland", "pl", 48, 0, R.drawable.pl),
			new Country("Portugal", "pt", 351, 0, R.drawable.pt),
			new Country("Puerto Rico", "pr", 1, 3, R.drawable.pr),
			new Country("Qatar", "qa", 974, 0, R.drawable.qa),
			new Country("Reunion", "re", 262, 0, R.drawable.re),
			new Country("Romania", "ro", 40, 0, R.drawable.ro),
			new Country("Russia", "ru", 7, 0, R.drawable.ru),
			new Country("Rwanda", "rw", 250, 0, R.drawable.rw),
			// new Country("Saint Barthélemy", "bl", 590, 1, R.drawable.bl),
			new Country("Saint Helena", "sh", 290, 0, R.drawable.sh),
			new Country("Saint Kitts and Nevis", "kn", 1869, 0, R.drawable.kn),
			new Country("Saint Lucia", "lc", 1758, 0, R.drawable.lc),
			// new Country("Saint Martin", "mf", 590, 2, R.drawable.mf),
			new Country("Saint Pierre and Miquelon", "pm", 508, 0, R.drawable.pm),
			new Country("Saint Vincent and the Grenadines", "vc", 1784, 0, R.drawable.vc),
			new Country("Samoa", "ws", 685, 0, R.drawable.ws),
			new Country("San Marino", "sm", 378, 0, R.drawable.sm),
			new Country("Sao Tome and Principe", "st", 239, 0, R.drawable.st),
			new Country("Saudi Arabia", "sa", 966, 0, R.drawable.sa),
			new Country("Senegal", "sn", 221, 0, R.drawable.sn),
			new Country("Serbia", "rs", 381, 0, R.drawable.rs),
			new Country("Seychelles", "sc", 248, 0, R.drawable.sc),
			new Country("Sierra Leone", "sl", 232, 0, R.drawable.sl),
			new Country("Singapore", "sg", 65, 0, R.drawable.sg),
			// new Country("Sint Maarten", "sx", 1721, 0, R.drawable.sx),
			new Country("Slovakia", "sk", 421, 0, R.drawable.sk),
			new Country("Slovenia", "si", 386, 0, R.drawable.si),
			new Country("Solomon Islands", "sb", 677, 0, R.drawable.sb),
			new Country("Somalia", "so", 252, 0, R.drawable.so),
			new Country("South Africa", "za", 27, 0, R.drawable.za),
			new Country("South Korea", "kr", 82, 0, R.drawable.kr),
			// new Country("South Sudan", "ss", 211, 0, R.drawable.ss),
			new Country("Spain", "es", 34, 0, R.drawable.es),
			new Country("Sri Lanka", "lk", 94, 0, R.drawable.lk),
			new Country("Sudan", "sd", 249, 0, R.drawable.sd),
			new Country("Suriname", "sr", 597, 0, R.drawable.sr),
			new Country("Swaziland", "sz", 268, 0, R.drawable.sz),
			new Country("Sweden", "se", 46, 0, R.drawable.se),
			new Country("Switzerland", "ch", 41, 0, R.drawable.ch),
			new Country("Syria", "sy", 963, 0, R.drawable.sy),
			new Country("Taiwan", "tw", 886, 0, R.drawable.tw),
			new Country("Tajikistan", "tj", 992, 0, R.drawable.tj),
			new Country("Tanzania", "tz", 255, 0, R.drawable.tz),
			new Country("Thailand", "th", 66, 0, R.drawable.th),
			new Country("Timor-Leste", "tl", 670, 0, R.drawable.tl),
			new Country("Togo", "tg", 228, 0, R.drawable.tg),
			new Country("Tokelau", "tk", 690, 0, R.drawable.tk),
			new Country("Tonga", "to", 676, 0, R.drawable.to),
			new Country("Trinidad and Tobago", "tt", 1868, 0, R.drawable.tt),
			new Country("Tunisia", "tn", 216, 0, R.drawable.tn),
			new Country("Turkey", "tr", 90, 0, R.drawable.tr),
			new Country("Turkmenistan", "tm", 993, 0, R.drawable.tm),
			new Country("Turks and Caicos Islands", "tc", 1649, 0, R.drawable.tc),
			new Country("Tuvalu", "tv", 688, 0, R.drawable.tv),
			new Country("U.S. Virgin Islands", "vi", 1340, 0, R.drawable.vi),
			new Country("Uganda", "ug", 256, 0, R.drawable.ug),
			new Country("Ukraine", "ua", 380, 0, R.drawable.ua),
			new Country("United Arab Emirates", "ae", 971, 0, R.drawable.ae),
			new Country("United Kingdom", "gb", 44, 0, R.drawable.gb),
			new Country("United States", "us", 1, 0, R.drawable.us),
			new Country("Uruguay", "uy", 598, 0, R.drawable.uy),
			new Country("Uzbekistan", "uz", 998, 0, R.drawable.uz),
			new Country("Vanuatu", "vu", 678, 0, R.drawable.vu),
			new Country("Vatican City", "va", 39, 1, R.drawable.va),
			new Country("Venezuela", "ve", 58, 0, R.drawable.ve),
			new Country("Vietnam", "vn", 84, 0, R.drawable.vn),
			new Country("Wallis and Futuna", "wf", 681, 0, R.drawable.wf),
			new Country("Yemen", "ye", 967, 0, R.drawable.ye),
			new Country("Zambia", "zm", 260, 0, R.drawable.zm),
			new Country("Zimbabwe", "zw", 263, 0, R.drawable.zw)
	};
}
